---
name: Macbook Pro Feet
description: |
  3d printable replacement feet for a macbook pro

  ## Installation

  - Print out 4 feet at high detail in TPU
  - Use E600 Glue or similar

  Its better to use too much glue than not enough. E600 glue dries to a rubber cement like consistency. If there is too much glue you can always peal away excess

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2022
resources:
  e600 glue: https://www.amazon.com/E6000-230010-Craft-Adhesive-Ounces/dp/B007TSYNG8
links:
  Thingiverse: https://www.thingiverse.com/thing:5192756
  Prusa: https://www.prusaprinters.org/prints/115863-macbook-pro-feet
  # GrabCad: https://foo.com
  # Hackster.io: https://hackster.io/foo
  # Hackaday: https://hackaday.io/foo
  # Reddit: https://www.reddit.com/r/foo
  Github: https://github.com/spuder/MBP-feet
  # Blog: https://foo.com
